name: BCC WP Proxy - Production

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: ${{ secrets.GCLOUD_APP_NAME }}

defaults:
  run:
    working-directory: ./src

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Run tests
#        run: |
#          if [ -f docker-compose.test.yml ]; then
#            docker-compose --file docker-compose.test.yml build
#            docker-compose --file docker-compose.test.yml run sut
#          else
#            docker build . --file Dockerfile
#          fi

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build_and_run:
    # Ensure test job passes before pushing image.
    #needs: test
    
    environment: bcc-wp-proxy

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
       
      - name: Authenticate into Google Cloud Platform
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          
      - name: Configure Docker to use Google Cloud Platform
        run: "gcloud auth configure-docker --quiet"
        
      - name: Push and deploy image
        run: |
          IMAGE_ID=eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          
          gcloud run deploy ${{ secrets.GCLOUD_APP_NAME }} --image $IMAGE_ID:$VERSION \
          --project ${{ secrets.GCLOUD_PROJECT }} \
          --region europe-north1 \
          --vpc-connector ${{ secrets.GCLOUD_VPC_CONNECTOR_NAME }} \
          --port 80 \
          --allow-unauthenticated \
          --update-env-vars GCP_ProjectID=${{ secrets.GCLOUD_PROJECT }} \
          --update-evn-var WPProxy__DestinationAddress=${{ secrets.PROXY_DESTINATION_ADDRESS }} \
          --update-evn-var WPProxy__ProxyAddress=${{ secrets.PROXY_ADDRESS }} \
          --update-evn-var WPProxy__UseRedis=true \
          --update-evn-var WPProxy__RedisInstanceName=${{ secrets.PROXY_REDIS_INSTANCE_NAME }} \
          --update-evn-var WPProxy__RedisIpAddress=${{ secrets.PROXY_REDIS_IP_ADDRESS }} \
          --update-evn-var WPProxy__RedisPort=${{ secrets.PROXY_REDIS_PORT }} \
          --update-evn-var WPProxy__ProxyKey=${{ secrets.PROXY_KEY }} \
          --update-evn-var WPProxy__GoogleStorageBucket=${{ secrets.PROXY_STORAGE_BUCKET_NAME }} \
          --update-evn-var Authentication_Authority=${{ secrets.AUTH_AUTHORITY }} \
          --update-evn-var Authentication_ClientId=${{ secrets.AUTH_CLIENT_ID }} \
          --update-evn-var Authentication_ClientSecret=${{ secrets.AUTH_CLIENT_SECRET }} \
          --platform managed
